function assert_unit_quadratic_forms(values,tolerance)
% @CRITERION COV-FINITE-001: finite real forms, |q-1| <= tolerance.
assert(isa(tolerance,'double') && isreal(tolerance) && isscalar(tolerance) ...
    && isfinite(tolerance) && tolerance>=0, ...
    'libtr:check:Tolerance','Expected finite nonnegative tolerance');
assert(isa(values,'double') && isreal(values) && ~isempty(values) ...
    && all(isfinite(values(:))) && all(abs(values(:)-1)<=tolerance), ...
    'libtr:check:QuadraticForm','Expected finite real quadratic forms within tolerance');
end