function selected = service_pipeline_select_test(request, root)
% Validate an optional explicit unit-test name, never a path or expression.
selected='';
if ~isfield(request,'test'), return; end
assert(strcmp(request.action,'unit') && ischar(request.test) && ...
    isrow(request.test) && ...
    ~isempty(regexp(request.test,'^unit_test_[A-Za-z0-9_]+$','once')), ...
    'libtr:pipeline:Test','Invalid test selection');
assert(isfile(fullfile(root,'matlab','tests',[request.test '.m'])), ...
    'libtr:pipeline:Test','Unknown unit test');
selected=request.test;
end